export enum IOEventName {
    WS_PRIVATE_EVENT = "PRIVATE",
    WS_PUBLIC_EVENT = "PUBLIC",
    WS_JOIN_EVENT = "JOIN",
    WS_CONNECT_EVENT = "ONLINE",
    WS_DISCONNECT_EVENT = "OFFLINE",
    WS_TYPING_EVENT = "TYPING",
    WS_SEEN = "SEEN",
}
